"""The storage interface, and what a storage reference is.

A dataset's bytes are written by the API and read back by the worker — a
different process, and once either scales past one machine, a different host.
Until this module existed, ``datasets.storage_ref`` held a filesystem path and
the worker opened it, which is correct exactly while the two share a filesystem.
The failure when they do not is the bad kind: the path resolves to nothing on the
worker's host and the run fails with a file-not-found that reads like data
corruption rather than like a deployment mistake.

So what the database records is a *storage reference*, not a path, and the only
thing allowed to interpret it is a store that recognises its scheme:

``local:datasets/<uuid>.csv``   a file beneath the configured upload directory
``s3://<bucket>/<key>``         an object in an S3-compatible bucket

Both are self-describing, which is the whole point. A worker configured for S3
that is handed a ``local:`` reference refuses outright instead of looking for a
file its host was never going to have — the same refuse-rather-than-repair rule
the estimation layers follow. A bare filesystem path is also accepted on read,
because rows written before this module existed contain one; see
:class:`~app.storage.local.LocalObjectStore`.

Both methods block. Callers on the event loop must go through
``asyncio.to_thread``, and the two that exist do.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

# Keys are generated by this application, never by a client — the stored object
# is named by a fresh UUID and the client's filename is metadata (using it as a
# path is how directory traversal gets in). The check below is therefore a guard
# against our own future mistakes rather than against a hostile caller, which is
# why it is strict enough to be boring: one flat alphabet, no empty segments, no
# parent references, no absolute paths, no backslashes.
_ALLOWED = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-/")


class StorageError(Exception):
    """Base for every failure raised by :mod:`app.storage`."""


class ObjectNotFound(StorageError):
    """The reference is well-formed but nothing is stored under it."""

    def __init__(self, ref: str) -> None:
        super().__init__(f"no stored object for reference {ref!r}")
        self.ref = ref


class UnusableReference(StorageError):
    """The reference belongs to a backend this store cannot read.

    Raised rather than guessed at. A run that fails with this message names a
    configuration mismatch — the process reading is not the kind of process that
    wrote — which is a far shorter path to the cause than an absent file.
    """


def validate_key(key: str) -> str:
    """Return ``key`` unchanged, or raise :class:`StorageError`."""

    if not key:
        raise StorageError("storage key is empty")
    if key.startswith("/") or ":" in key or "\\" in key:
        raise StorageError(f"storage key must be relative and unqualified: {key!r}")
    segments = key.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise StorageError(f"storage key has an empty or relative segment: {key!r}")
    if not set(key) <= _ALLOWED:
        raise StorageError(f"storage key has characters outside the allowed set: {key!r}")
    return key


class ObjectStore(ABC):
    """Put bytes under a key; get bytes back by reference.

    Deliberately two methods. There is no ``delete``, no ``list`` and no
    ``exists``: nothing in the application needs them, and an unused method on an
    interface with two implementations is two things to keep honest for no
    caller's benefit.
    """

    @abstractmethod
    def put(self, key: str, data: bytes) -> str:
        """Store ``data`` under ``key`` and return the reference to record.

        The returned reference — not the key — is what belongs in the database.
        """

    @abstractmethod
    def get(self, ref: str) -> bytes:
        """Return the bytes stored under ``ref``.

        Raises :class:`ObjectNotFound` if the reference resolves to nothing, and
        :class:`UnusableReference` if it names a backend this store is not.
        """
