"""
Tests for item fit.

The hard requirement on a fit statistic is a pair of opposing properties: it
must stay quiet when the model is right, and it must fire when the model is
wrong. A statistic that only ever flags is as useless as one that never does,
so both directions are tested for each of the three.
"""

from __future__ import annotations

import itertools

import numpy as np
import pytest

from app.irt.em import MISSING, fit
from app.irt.families import ItemParameters, ModelKey
from app.irt.simulate import TrueParameters, simulate, spread_parameters
from app.psychometrics.information import category_probabilities
from app.psychometrics.itemfit import _lord_wingersky, item_fit


def _brute_force_score_distribution(probs: list[np.ndarray], node: int) -> np.ndarray:
    """Enumerate every response pattern - only tractable for a toy test."""
    n_cat = [p.shape[1] for p in probs]
    max_score = sum(c - 1 for c in n_cat)
    out = np.zeros(max_score + 1)
    for pattern in itertools.product(*[range(c) for c in n_cat]):
        likelihood = np.prod([probs[j][node, k] for j, k in enumerate(pattern)])
        out[sum(pattern)] += likelihood
    return out


def test_lord_wingersky_matches_brute_force_enumeration():
    """The recursion must reproduce what enumerating every pattern would give."""
    items = [
        ItemParameters(item_id=f"i{k}", model=ModelKey.TWO_PL,
                       discrimination=a, difficulty=b)
        for k, (a, b) in enumerate([(1.2, -0.5), (0.8, 0.3), (1.6, 1.0)])
    ]
    graded = ItemParameters(
        item_id="g", model=ModelKey.GRM, discrimination=1.1,
        thresholds=[-0.8, 0.4], n_categories=3,
    )
    nodes = np.linspace(-2, 2, 5)
    probs = [category_probabilities(p, nodes) for p in [*items, graded]]

    recursion = _lord_wingersky(probs)

    assert recursion.shape == (5, 3 + 2 + 1)
    np.testing.assert_allclose(recursion.sum(axis=1), 1.0, atol=1e-12)
    for node in range(5):
        np.testing.assert_allclose(
            recursion[node], _brute_force_score_distribution(probs, node),
            atol=1e-12,
        )


def test_well_fitting_items_are_quiet():
    """Data generated by the model being fitted should not raise flags."""
    true = spread_parameters(ModelKey.TWO_PL, 20)
    data, _ = simulate(true, 2000, seed=101)
    result = fit(data, ModelKey.TWO_PL)
    assert result.converged

    report = item_fit(data, result.item_parameters)

    infit = np.array([i.infit for i in report.items])
    outfit = np.array([i.outfit for i in report.items])
    rmsd = np.array([i.rmsd for i in report.items])

    assert np.abs(infit - 1.0).max() < 0.15
    assert np.abs(outfit - 1.0).max() < 0.20
    assert rmsd.max() < 0.06
    # At most the odd item by chance, not a wholesale flagging.
    assert len(report.flagged) <= 2


def test_misfitting_item_is_caught():
    """An item whose discrimination the fitted model cannot represent must flag.

    Rasch forces every slope to 1. An item generated with a slope far from 1 is
    therefore genuinely misfit under it, and all three statistics should say so
    for that item and not for its neighbours.
    """
    n_items = 20
    a = np.full(n_items, 1.0)
    a[7] = 0.25       # near-flat: responses barely relate to the trait
    a[13] = 2.8       # far steeper than Rasch can express
    true = TrueParameters(
        model=ModelKey.TWO_PL,
        discrimination=a,
        difficulty=np.linspace(-1.8, 1.8, n_items),
    )
    data, _ = simulate(true, 3000, seed=103)

    result = fit(data, ModelKey.RASCH)
    assert result.converged
    report = item_fit(data, result.item_parameters)

    outfit = np.array([i.outfit for i in report.items])
    rmsd = np.array([i.rmsd for i in report.items])
    z = np.array([i.s_x2_z for i in report.items])

    # The flat item is over-noisy, the steep one over-predictable.
    assert outfit[7] > 1.25
    assert outfit[13] < 0.80

    # Both aberrant items are the two most extreme on every statistic.
    assert set(np.argsort(np.abs(outfit - 1.0))[-2:].tolist()) == {7, 13}
    assert set(np.argsort(z)[-2:].tolist()) == {7, 13}
    assert {7, 13}.issubset(set(np.argsort(rmsd)[-4:].tolist()))

    # Clean items stay quiet: the model is right for all eighteen of them.
    assert np.abs(np.delete(outfit, [7, 13]) - 1.0).max() < 0.15
    assert np.abs(np.delete(z, [7, 13])).max() < 6.0

    assert result.item_parameters[7].item_id in {
        i.item_id for i in report.flagged
    }


def test_over_discrimination_escapes_the_mean_square_range():
    """The conventional 0.7-1.3 mean-square band is porous in one direction.

    An item that discriminates far *better* than the fitted model allows is
    genuinely misfitting, but its residuals are unusually small, so its
    mean-squares drift towards the lower edge of the conventional band rather
    than past it. S-X2 has no such blind spot. This test pins the asymmetry so
    that nobody later "simplifies" the report down to mean-squares alone.
    """
    n_items = 20
    a = np.full(n_items, 1.0)
    a[13] = 2.8
    true = TrueParameters(
        model=ModelKey.TWO_PL,
        discrimination=a,
        difficulty=np.linspace(-1.8, 1.8, n_items),
    )
    data, _ = simulate(true, 3000, seed=103)
    result = fit(data, ModelKey.RASCH)
    report = item_fit(data, result.item_parameters)

    entry = report.items[13]
    # Inside the conventional band, or close enough that a reader would pass it.
    assert entry.outfit > 0.65
    # But unambiguous on the statistic that conditions on an observed score.
    assert entry.s_x2_z > 20.0
    assert entry.s_x2_p < 1e-6


def test_s_x2_degrees_of_freedom_account_for_estimated_parameters():
    true = spread_parameters(ModelKey.TWO_PL, 15)
    data, _ = simulate(true, 1500, seed=107)
    result = fit(data, ModelKey.TWO_PL)

    report = item_fit(data, result.item_parameters)

    for entry in report.items:
        assert entry.s_x2 is not None, entry.notes
        assert entry.s_x2_df is not None and entry.s_x2_df >= 1
        assert entry.s_x2 >= 0.0
        assert 0.0 <= entry.s_x2_p <= 1.0
        # z is the standardised form: (X2 - df) / sqrt(2 df).
        assert entry.s_x2_z == pytest.approx(
            (entry.s_x2 - entry.s_x2_df) / np.sqrt(2 * entry.s_x2_df)
        )


def test_s_x2_is_calibrated_when_the_model_is_true():
    """Under a correct model the standardised statistic should hover near zero.

    This is the check that catches degrees of freedom being counted wrongly - a
    df error shifts every item's z in the same direction, which shows up in the
    mean even though no single item looks unusual.
    """
    true = spread_parameters(ModelKey.TWO_PL, 20)
    data, _ = simulate(true, 3000, seed=109)
    result = fit(data, ModelKey.TWO_PL)

    report = item_fit(data, result.item_parameters)
    z = np.array([i.s_x2_z for i in report.items])

    assert abs(np.mean(z)) < 1.0


def test_polytomous_item_fit_runs_and_is_quiet():
    true = spread_parameters(ModelKey.GRM, 10, n_categories=4)
    data, _ = simulate(true, 2000, seed=113)
    result = fit(data, ModelKey.GRM)
    assert result.converged

    report = item_fit(data, result.item_parameters)

    assert all(i.rmsd is not None for i in report.items)
    assert all(i.s_x2 is not None for i in report.items), [
        i.notes for i in report.items
    ]
    assert np.abs([i.infit for i in report.items] - np.ones(10)).max() < 0.15


def test_missing_data_is_reported_not_hidden():
    """S-X2 cannot use incomplete cases, and must say how many it dropped."""
    true = spread_parameters(ModelKey.TWO_PL, 15)
    data, _ = simulate(true, 1200, seed=127, missing_rate=0.10)

    result = fit(data, ModelKey.TWO_PL)
    report = item_fit(data, result.item_parameters)

    assert report.n_persons_complete < data.n_persons
    assert any("no missing responses" in n for n in report.notes)
    # The mean-squares still use every observed response.
    assert all(i.n_used > report.n_persons_complete for i in report.items)


def test_small_sample_refuses_s_x2_rather_than_guessing():
    true = spread_parameters(ModelKey.TWO_PL, 10)
    data, _ = simulate(true, 40, seed=131)
    result = fit(data, ModelKey.TWO_PL)
    if not result.converged:
        pytest.skip("fit did not converge at n=40, which is itself acceptable")

    report = item_fit(data, result.item_parameters)

    assert all(i.s_x2 is None for i in report.items)
    assert all(
        any("50 complete cases" in n for n in i.notes) for i in report.items
    )
    # But the sample-size-free statistics still come through.
    assert all(i.rmsd is not None for i in report.items)


def test_rejects_mismatched_parameter_count():
    true = spread_parameters(ModelKey.TWO_PL, 10)
    data, _ = simulate(true, 300, seed=137)
    result = fit(data, ModelKey.TWO_PL)

    with pytest.raises(ValueError, match="for 10 columns"):
        item_fit(data, result.item_parameters[:5])
