"""Initial schema.

The v1 repository declared alembic as a dependency, had no ``alembic/``
directory, and built its schema with ``create_all`` (P5) — there was no way to
change a live database. This is the migration that ends that: every table in
:mod:`app.db.models` at the point the v2 API was written.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-05

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stakes_level', sa.Enum('low', 'medium', 'high', name='stakeslevel', native_enum=False, length=20), nullable=False),
    sa.Column('intended_use', sa.Enum('research', 'operational', 'certification', name='intendeduse', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('n_persons', sa.Integer(), nullable=False),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('column_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('n_items > 0', name='ck_datasets_n_items_positive'),
    sa.CheckConstraint('n_persons > 0', name='ck_datasets_n_persons_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index('ix_datasets_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='runstatus', native_enum=False, length=20), nullable=False),
    sa.Column('requested_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('queue_job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_analysis_runs_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)

    op.create_table('diagnostics_blobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostics_blobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostics_blobs_run_id'), ['run_id'], unique=True)

    op.create_table('model_fits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('model_key', sa.String(length=20), nullable=False),
    sa.Column('converged', sa.Boolean(), nullable=False),
    sa.Column('n_cycles', sa.Integer(), nullable=True),
    sa.Column('log_likelihood', sa.Float(), nullable=True),
    sa.Column('n_free_parameters', sa.Integer(), nullable=True),
    sa.Column('n_persons', sa.Integer(), nullable=True),
    sa.Column('aic', sa.Float(), nullable=True),
    sa.Column('bic', sa.Float(), nullable=True),
    sa.Column('latent_sd', sa.Float(), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_fits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_fits_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_model_fits_run_model', ['run_id', 'model_key'], unique=True)

    op.create_table('item_parameters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fit_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('n_categories', sa.Integer(), nullable=False),
    sa.Column('discrimination', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('guessing', sa.Float(), nullable=True),
    sa.Column('thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('se_discrimination', sa.Float(), nullable=True),
    sa.Column('se_difficulty', sa.Float(), nullable=True),
    sa.Column('se_guessing', sa.Float(), nullable=True),
    sa.Column('se_thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['fit_id'], ['model_fits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_parameters_fit_id'), ['fit_id'], unique=False)
        batch_op.create_index('ix_item_parameters_fit_position', ['fit_id', 'position'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_parameters', schema=None) as batch_op:
        batch_op.drop_index('ix_item_parameters_fit_position')
        batch_op.drop_index(batch_op.f('ix_item_parameters_fit_id'))

    op.drop_table('item_parameters')
    with op.batch_alter_table('model_fits', schema=None) as batch_op:
        batch_op.drop_index('ix_model_fits_run_model')
        batch_op.drop_index(batch_op.f('ix_model_fits_run_id'))

    op.drop_table('model_fits')
    with op.batch_alter_table('diagnostics_blobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostics_blobs_run_id'))

    op.drop_table('diagnostics_blobs')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_owner_id'))
        batch_op.drop_index('ix_analysis_runs_owner_created')
        batch_op.drop_index(batch_op.f('ix_analysis_runs_dataset_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_owner_id'))
        batch_op.drop_index('ix_datasets_owner_created')

    op.drop_table('datasets')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_index('ix_projects_owner_created')

    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
